### ISSUE TITLE
Unable to generate correlation table

### ISSUE THREAD

**Issue by JayashreeRegoti** [JayashreeRegoti/neocortexapi#2]
Hello Professor,

I have created 2 sets of input images, in one set I have shifted the rectangular box to its right,

![image](https://user-images.githubusercontent.com/56843949/122673972-681d7e00-d1d3-11eb-868c-47fac1c93520.png)
![image](https://user-images.githubusercontent.com/56843949/122673977-74094000-d1d3-11eb-9712-2d59a1edc82f.png)
 
here is the corresponding correlation table

![image](https://user-images.githubusercontent.com/56843949/122674090-eb3ed400-d1d3-11eb-8fec-37d243d0bb75.png)
![image](https://user-images.githubusercontent.com/56843949/122674102-fa258680-d1d3-11eb-851e-785254334749.png)

Here is the set of another images I am trying to give
![image](https://user-images.githubusercontent.com/56843949/122674865-35758480-d1d7-11eb-9854-0e6daa88351a.png)
![image](https://user-images.githubusercontent.com/56843949/122674900-60f86f00-d1d7-11eb-97ed-61a2ea29cde1.png)
![image](https://user-images.githubusercontent.com/56843949/122674917-766d9900-d1d7-11eb-842f-3e6e633aeb56.png)

However, the corresponding output table is not generating. I am not sure why. Can you suggest to me something that I can do to make this work.

Here is the link for my SpatialSimilarity.cs file
https://github.com/JayashreeRegoti/neocortexapi/blob/master/NeoCortexApi/NeoCortexApi.Experiments/SpatialSimilarityExperiment.cs
 and the link for input images
https://github.com/JayashreeRegoti/neocortexapi/tree/master/NeoCortexApi/NeoCortexApi.Experiments/TestData/SpatialSimilarityExperiment

Regards,
JayashreeRegoti

**Comment by ddobric** [comment]
closing
